//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Textos
    {
        public int Id { get; set; }
        public string Texto { get; set; }
        public string Local { get; set; }
        public string Pagina { get; set; }
    }
}
